const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  getProjects: () => ipcRenderer.invoke('get-projects'),
  getSprints: (project) => ipcRenderer.invoke('get-sprints', project),
  getHus: (data) => ipcRenderer.invoke('get-hus', data),
  createProject: (name) => ipcRenderer.invoke('create-project', name),
  renameProject: (data) => ipcRenderer.invoke('rename-project', data),
  deleteProject: (name) => ipcRenderer.invoke('delete-project', name),
  createSprint: (data) => ipcRenderer.invoke('create-sprint', data),
  renameSprint: (data) => ipcRenderer.invoke('rename-sprint', data),
  deleteSprint: (data) => ipcRenderer.invoke('delete-sprint', data),
  createHu: (data) => ipcRenderer.invoke('create-hu', data),
  renameHu: (data) => ipcRenderer.invoke('rename-hu', data),
  deleteHu: (data) => ipcRenderer.invoke('delete-hu', data),
  uploadFile: (data) => ipcRenderer.invoke('upload-file', data),
  selectFiles: () => ipcRenderer.invoke('select-files'),
  selectProjectZip: () => ipcRenderer.invoke('select-project-zip'),
  selectProjectFolder: () => ipcRenderer.invoke('select-project-folder'),
  importProject: (data) => ipcRenderer.invoke('import-project', data),
  selectExportPath: (defaultName) => ipcRenderer.invoke('select-export-path', defaultName),
  exportProject: (data) => ipcRenderer.invoke('export-project', data),
  generateAudioGuide: (data) => ipcRenderer.invoke('generate-audio-guide', data),
  loadAudioGuide: (data) => ipcRenderer.invoke('load-audio-guide', data),
  getScreenSources: () => ipcRenderer.invoke('get-screen-sources'),
  saveRecording: (data) => ipcRenderer.invoke('save-recording', data),
  startRecording: (data) => ipcRenderer.invoke('start-recording', data),
  updateOverlayText: (text) => ipcRenderer.invoke('update-overlay-text', text),
  onOverlayControl: (cb) => ipcRenderer.on('overlay-control', (_e, action) => cb(action)),
  selectVideoFile: () => ipcRenderer.invoke('select-video-file'),
  trimVideo: (data) => ipcRenderer.invoke('trim-video', data),
  saveAnnotatedFrame: (data) => ipcRenderer.invoke('save-annotated-frame', data),
  listHuEvidence: (data) => ipcRenderer.invoke('list-hu-evidence', data),
  deleteHuEvidence: (data) => ipcRenderer.invoke('delete-hu-evidence', data),
  readEvidenceMeta: (data) => ipcRenderer.invoke('read-evidence-meta', data),
  updateEvidenceMeta: (data) => ipcRenderer.invoke('update-evidence-meta', data),
  organizeInsumos: (data) => ipcRenderer.invoke('organize-insumos', data),
  generateEvidence: (data) => ipcRenderer.invoke('generate-evidence', data),
  parseExcel: (data) => ipcRenderer.invoke('parse-excel', data),
  saveTestCases: (data) => ipcRenderer.invoke('save-test-cases', data),
  loadTestCases: (data) => ipcRenderer.invoke('load-test-cases', data),
  getProjectDetails: (project) => ipcRenderer.invoke('get-project-details', project),
  getSprintSummary: (project, sprint) => ipcRenderer.invoke('get-sprint-summary', { project, sprint }),
  loadTrazabilidad: () => ipcRenderer.invoke('load-trazabilidad'),
  createDetachedView: (tabId) => ipcRenderer.invoke('create-detached-view', { tabId }),
  closeDetachedView: (tabId) => ipcRenderer.invoke('close-detached-view', { tabId }),
  onTabDetachedClosed: (cb) => ipcRenderer.on('tab-detached-closed', (_e, data) => cb(data)),
  saveRecordingContext: (data) => ipcRenderer.invoke('save-recording-context', data),
  getRecordingContext: () => ipcRenderer.invoke('get-recording-context'),
});